#!/bin/bash
set -euo pipefail

# Author: Jens Willemsens <jens@jensw.be>
# cURL commands: https://code.blogs.iiidefix.net/posts/webdav-with-curl/

# ===== OPTIONS =====
# General
BACKUPDIR=$(date +"%Y%m%d_%H%M%S")

# WebDAV
DAVUSER='JensWillemsens'
DAVPASS='<REPLACE ME>'
DAVURL='https://jenswillemsens.stackstorage.com/remote.php/webdav'
CURLOPTS="--silent --show-error -o /dev/null -Iw %{http_code} -u ${DAVUSER}:${DAVPASS}"

# GPG (Password and options for output)
GPGPASS='<REPLACE ME>'
GPGOPT="--cipher-algo AES256 --compress-algo BZIP2 --batch --passphrase ${GPGPASS} -c"

# Nextcloud
NCBASE='/media/data/services/nextcloud'
NCURL="nextcloud.jensw.eu"
NCUSER='jens'
NCPASS='<REPLACE ME>'
NCCONTACTS=( "Persoonlijk" )
NCCALS=( "persoonlijk" "thuis" "werk" )

# SQL (Read access on Nextcloud DB)
SQLUSER='nextcloud'
SQLPASS='<REPLACE ME>'
SQLCONTAINER='mariadb'


# ===== cURL webdav helper functions =====
# Create a new directory
function dav_create_dir () {
  STATUS=$(curl -X MKCOL ${CURLOPTS} "${DAVURL}/$1")

  if [ ${STATUS} -ne 201 ]; then
    echo "Creating dir \"$1\" gave status ${STATUS}"
    exit 1
  fi
}

# Upload file
function dav_upload_file () {
  STATUS=$(curl -T $1 ${CURLOPTS} "${DAVURL}/")
  
  if [ ${STATUS} -ne 201 ]; then
    echo "Uploading file \"$1\" gave status ${STATUS}"
    exit 1
  fi
}

# Encrypt STDIN and send to WebDAV
function dav_encrypt_upload_stdin () {
  STATUS=$(gpg ${GPGOPT} | curl -T - ${CURLOPTS} "${DAVURL}/$1")
  
  if [ ${STATUS} -ne 201 ]; then
    echo "Uploading stdin to \"$1\" gave status ${STATUS}"
    exit 1
  fi
}


# ===== Script =====
# Create dir for today
dav_create_dir ${BACKUPDIR}

# Backup database
docker exec ${SQLCONTAINER} mysqldump -u ${SQLUSER} -p${SQLPASS} nextcloud |  dav_encrypt_upload_stdin "${BACKUPDIR}/db_nextcloud.sql.gpg"

# Backup contacts
dav_create_dir "${BACKUPDIR}/contacts"
for NCCONTACT in "${NCCONTACTS[@]}"; do
    curl --silent --show-error -u "${NCUSER}:${NCPASS}" "https://${NCURL}/remote.php/dav/addressbooks/users/${NCUSER}/${NCCONTACT}?export" | dav_encrypt_upload_stdin "${BACKUPDIR}/contacts/${NCCONTACTS}.vcf.gpg"
done

# Backup calendars
dav_create_dir "${BACKUPDIR}/cals"
for NCCAL in "${NCCALS[@]}"; do
    curl --silent --show-error -u "${NCUSER}:${NCPASS}" "https://${NCURL}/remote.php/dav/calendars/${NCUSER}/${NCCAL}?export" | dav_encrypt_upload_stdin "${BACKUPDIR}/cals/$NCCAL.ical.gpg"
done

# Backup files
cat "${NCBASE}/${NCUSER}/files/IT/JensWillemsens.kdbx" | dav_encrypt_upload_stdin "${BACKUPDIR}/JensWillemsens.kdbx.gpg"
tar -c -C "${NCBASE}/${NCUSER}/files/Notes/" . | dav_encrypt_upload_stdin "${BACKUPDIR}/notes.tar.gpg"

# Backup documents
if [ $(date +%u) -eq  1 ]; then
    # Monday, full backup
    if [ -e "/tmp/documents-full.tar.gpg" ]; then
      shred -u  "/tmp/documents-full.tar.gpg" 2> /dev/null
    fi
    tar -c -C "${NCBASE}/${NCUSER}/files/Documenten/" -g /root/documents.snar-0 --level=0 . | gpg -o "/tmp/documents-full.tar.gpg" ${GPGOPT}
    dav_upload_file "/tmp/documents-full.tar.gpg"
    shred -u  "/tmp/documents-full.tar.gpg"
else
    # Other day, incremental
    if [ -e "/tmp/documents-inc.tar.gpg" ]; then
      shred -u  "/tmp/documents-inc.tar.gpg" 2> /dev/null
    fi
    cp -f /root/documents.snar-0 /root/documents.snar-1
    tar -c -C "${NCBASE}/${NCUSER}/files/Documenten/" -g /root/documents.snar-1 . | gpg -o "/tmp/documents-inc.tar.gpg" ${GPGOPT}
    dav_upload_file "/tmp/documents-inc.tar.gpg"
    shred -u  "/tmp/documents-inc.tar.gpg"
fi
